# Generated by Django 5.0.4 on 2024-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del empleado')),
                ('idcorreo', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Correo')),
                ('contrasena_hashed', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
        ),
    ]
